ARG FROM_REGISTRY
ARG FROM_IMAGE_NAME

FROM $FROM_REGISTRY/$FROM_IMAGE_NAME:7.1

MAINTAINER Daniel Rose <daniel-rose@gmx.de>

RUN set -ex

COPY supervisord.conf /etc/supervisor/conf.d/jenkins-slave.conf
COPY docker-entrypoint.sh /usr/local/bin/

CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"]