ARG FROM_REGISTRY
ARG FROM_IMAGE_NAME

FROM $FROM_REGISTRY/$FROM_IMAGE_NAME:7.1

MAINTAINER Daniel Rose <daniel-rose@gmx.de>

RUN set -ex

RUN apt-get update; \
    apt-get install -y \
        ruby \
        ruby-dev \
        build-essential \
        libsqlite3-dev

RUN rm -rf /var/lib/apt/lists/*

# mailcatcher client
RUN gem install mailcatcher

COPY php.ini /usr/local/etc/php/php.ini

COPY supervisord.conf /etc/supervisor/conf.d/jenkins-slave.conf